export default Object.freeze({
  is_main: false,
  id: null,
  title: '',
  created_at: '',
  body_html: '',
  blog_id: null,
  author: '',
  user_id: null,
  published_at: '',
  updated_at: '',
  template_suffix: null,
  handle: '',
  tags: '',
  image: '',
  comments: [],
  comments_count: 0,
  comments_enabled: false,
  comments_post_url: '',
  excerpt: '',
  image_alt: '',
  moderated: false,
  url: '',
  user: null,
});
