export default Object.freeze({
  all_products_count: 0,
  all_tags: [],
  all_types: [],
  all_vendors: [],
  current_tags: '',
  current_type: '',
  current_vendor: '',
  default_sort_by: 'best-selling',
  description: '',
  disjunctive: false,
  handle: '',
  id: null,
  image: '',
  items_per_page: 50,
  page: 1,
  products_count: 0,
  products_handles: [],
  products: [],
  published_at: '',
  published_scope: '',
  sort_by: 'best-selling',
  sort_options: [
    { value: 'manual', name: 'Featured' },
    { value: 'best-selling', name: 'Best selling' },
    { value: 'title-ascending', name: 'Alphabetically, A-Z' },
    { value: 'title-descending', name: 'Alphabetically, Z-A' },
    { value: 'price-ascending', name: 'Price, low to high' },
    { value: 'price-descending', name: 'Price, high to low' },
    { value: 'created-ascending', name: 'Date, old to new' },
    { value: 'created-descending', name: 'Date, new to old' },
  ],
  tags: [],
  template_suffix: '',
  title: '',
  updated_at: '',
  view_type: 'grid',
});
